const products = [
    {
        id:1,
        couleur:'noir',
        sexe:'Homme',
        collection:'2',
        description:'Bracelet en cuir Homme',
        caracteristique:['Bracelet en cuir Homme'],
        prix:35000,
        image:['img/watche5.jpeg'],
    },
    {
        id:2,
        couleur:'Marron',
        sexe:'Homme',
        collection:'2',
        description:'Bracelet en cuir Homme',
        caracteristique:['Bracelet en cuir Homme'],
        prix:35000,
        image:'img/watche6.jpeg',
    },
   
    {
        id:3,
        couleur:'Blanc',
        sexe:'Femme',
        collection:'2',
        description:'Bracelet en cuir Femme',
        caracteristique:['Bracelet en cuir '],
        prix:35000,
        image:'img/watche7.jpeg',
    },
    {
        id:4,
        couleur:'noir',
        sexe:'Femme',
        collection:'2',
        description:'Bracelet en cuir Femme',
        caracteristique:['Bracelet en cuir '],
        prix:0,
        image:'img/watche8.jpeg',
    }]